### PR TITLE
feat: add disabled flag

### PR DESCRIPTION
**Pull request by thejoeejoee**
- based on #102 
- removed conflicts
- add docs

@iliyaZelenko, is here anything else what I should add since origin PR is marked as help-wanted?

### CODE REVIEW

**Comment by iliyaZelenko** [comment]
@thejoeejoee hi, it looks good! Thanks for the work done, I'm glad you noticed that I added help-wanted label. 

>  is here anything else what I should add

The only thing that comes to the head, but with which I'm not sure, is to somehow style the content through CSS, so that it is more clearly visible that the content is not editable. For example, just do     `cursor: not-allowed`. Maybe you have some ideas.

**Comment by thejoeejoee** [comment]
Well, I've added `cursor: not-allowed` for entire editor and also light gray overlay to the entire component -- colors are taken from Vuetify light theme.
obrazek

**Comment by iliyaZelenko** [comment]
Great work, I watched how it works by running the project and I like it! Also, I have no complaints about the code, everything is fine.

**Pull request merged**
