### PR TITLE
Added Swedish language support

### PR DESCRIPTION
**Pull request by jnyblom**

### CODE REVIEW

**Comment by iliyaZelenko** [comment]
@jnyblom It looks cool! You forgot to add a few small changes to other files, [example](https://github.com/iliyaZelenko/tiptap-vuetify/pull/118/files). When you are done, I will gladly accept your changes!

**Comment by jnyblom** [comment]
Sorry for the delay!

**Comment by iliyaZelenko** [comment]
Very well! Thanks, @jnyblom.

**Pull request merged**
